services:
  postgres:
    image: 'postgres:15'
    environment:
      - 'POSTGRES_DB=sportify'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=root'
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: