spring:
  application:
    name: sportify
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false

server:
  port: ${SERVER_PORT:8080}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

provisorr:
  jwtSecret: ${PROVISORR_JWT_SECRET}
  jwtExpirationMs: ${PROVISORR_JWT_EXPIRATION_MS}
  jwtRefreshExpirationMs: ${PROVISORR_JWT_REFRESH_EXPIRATION_MS}



logging:
  level:
    root: INFO
    org.springframework.boot.context.config: DEBUG
