spring:
  application:
    name: sportify
  datasource:
    url: jdbc:postgresql://localhost:5432/sportify
    username: root
    password: secret
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true



server:
    port: 8080

springdoc:
    swagger-ui:
        path: /swagger-ui.html

#  springdoc.swagger-ui.path=/swagger-ui.html