spring:
  application:
    name: sportify
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sportify}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:secret}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false

server:
  port: ${SERVER_PORT:8090}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

provisorr:
  jwtSecret: ${PROVISORR_JWT_SECRET:YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY3ODkwYWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY3ODkw}
  jwtExpirationMs: ${PROVISORR_JWT_EXPIRATION_MS:86400000}
  jwtRefreshExpirationMs: ${PROVISORR_JWT_REFRESH_EXPIRATION_MS:604800000}



logging:
  level:
    root: INFO
    org.springframework.boot.context.config: DEBUG
