spring:
  application:
    name: sportify
  datasource:
    url: jdbc:postgresql://localhost:5432/sportify
    username: root
    password: secret
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false



server:
    port: 8080

springdoc:
    swagger-ui:
        path: /swagger-ui.html


provisorr:
  jwtSecret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY3ODkwYWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY3ODkw
  jwtExpirationMs: 86400000
  jwtRefreshExpirationMs : 604800000
#  springdoc.swagger-ui.path=/swagger-ui.html